/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(Hermitian_Symmetry_i_o_same_vec_size_cpvolk.h) */
/* BINDTOOL_HEADER_FILE_HASH(b4fb2f99d8fcd1624305b9c1d313f096) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/Hermitian_Symmetry_i_o_same_vec_size_cpvolk.h>
// pydoc.h is automatically generated in the build directory
#include <Hermitian_Symmetry_i_o_same_vec_size_cpvolk_pydoc.h>

void bind_Hermitian_Symmetry_i_o_same_vec_size_cpvolk(py::module &m) {

  using Hermitian_Symmetry_i_o_same_vec_size_cpvolk =
      ::gr::owc::Hermitian_Symmetry_i_o_same_vec_size_cpvolk;

  py::class_<Hermitian_Symmetry_i_o_same_vec_size_cpvolk, gr::sync_block,
             gr::block, gr::basic_block,
             std::shared_ptr<Hermitian_Symmetry_i_o_same_vec_size_cpvolk>>(
      m, "Hermitian_Symmetry_i_o_same_vec_size_cpvolk",
      D(Hermitian_Symmetry_i_o_same_vec_size_cpvolk))

      .def(py::init(&Hermitian_Symmetry_i_o_same_vec_size_cpvolk::make),
           py::arg("fft_len"), py::arg("use_negative_coefficients"),
           D(Hermitian_Symmetry_i_o_same_vec_size_cpvolk, make))

      ;
}
