/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(Hermitian_Symmetry_i_o_same_vec_size_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(7ce1ee6b0c5eaa5f013b2c4c1915cc9a) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/Hermitian_Symmetry_i_o_same_vec_size_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <Hermitian_Symmetry_i_o_same_vec_size_cplus_pydoc.h>

void bind_Hermitian_Symmetry_i_o_same_vec_size_cplus(py::module &m) {

  using Hermitian_Symmetry_i_o_same_vec_size_cplus =
      ::gr::owc::Hermitian_Symmetry_i_o_same_vec_size_cplus;

  py::class_<Hermitian_Symmetry_i_o_same_vec_size_cplus, gr::sync_block,
             gr::block, gr::basic_block,
             std::shared_ptr<Hermitian_Symmetry_i_o_same_vec_size_cplus>>(
      m, "Hermitian_Symmetry_i_o_same_vec_size_cplus",
      D(Hermitian_Symmetry_i_o_same_vec_size_cplus))

      .def(py::init(&Hermitian_Symmetry_i_o_same_vec_size_cplus::make),
           py::arg("fft_len"), py::arg("use_negative_coefficients"),
           D(Hermitian_Symmetry_i_o_same_vec_size_cplus, make))

      ;
}
