/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(LED_Nonlinearity.h) */
/* BINDTOOL_HEADER_FILE_HASH(1096d5fcd220c135ce7b10981f48cd14) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/LED_Nonlinearity.h>
// pydoc.h is automatically generated in the build directory
#include <LED_Nonlinearity_pydoc.h>

void bind_LED_Nonlinearity(py::module &m) {

  using LED_Nonlinearity = ::gr::owc::LED_Nonlinearity;

  py::class_<LED_Nonlinearity, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<LED_Nonlinearity>>(m, "LED_Nonlinearity",
                                                D(LED_Nonlinearity))

      .def(py::init(&LED_Nonlinearity::make), py::arg("L"), py::arg("k"),
           py::arg("x0"), D(LED_Nonlinearity, make))

      ;
}
