/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(OOK_Demodulator_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(6eaafcdd1fbc31934f9be6b4e8455310) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/OOK_Demodulator_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <OOK_Demodulator_cplus_pydoc.h>

void bind_OOK_Demodulator_cplus(py::module &m) {

  using OOK_Demodulator_cplus = ::gr::owc::OOK_Demodulator_cplus;

  py::class_<OOK_Demodulator_cplus, gr::sync_decimator,
             std::shared_ptr<OOK_Demodulator_cplus>>(m, "OOK_Demodulator_cplus",
                                                     D(OOK_Demodulator_cplus))

      .def(py::init(&OOK_Demodulator_cplus::make), py::arg("threshold"),
           py::arg("samples_per_symbol"), D(OOK_Demodulator_cplus, make))

      .def("set_threshold", &OOK_Demodulator_cplus::set_threshold,
           py::arg("threshold"), D(OOK_Demodulator_cplus, set_threshold))

      .def("threshold", &OOK_Demodulator_cplus::threshold,
           D(OOK_Demodulator_cplus, threshold))

      ;
}
