/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(OWC_Channel_relative_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(c3167289b59960321b18c4ce805dae93) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/OWC_Channel_relative_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <OWC_Channel_relative_cplus_pydoc.h>

void bind_OWC_Channel_relative_cplus(py::module &m) {

  using OWC_Channel_relative_cplus = ::gr::owc::OWC_Channel_relative_cplus;

  py::class_<OWC_Channel_relative_cplus, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<OWC_Channel_relative_cplus>>(
      m, "OWC_Channel_relative_cplus", D(OWC_Channel_relative_cplus))

      .def(py::init(&OWC_Channel_relative_cplus::make), py::arg("num_inputs"),
           py::arg("num_outputs"), py::arg("emission_angle_array"),
           py::arg("acceptance_angle_array"), py::arg("distance_array"),
           py::arg("lambertian_order_array"), py::arg("photosensor_area_array"),
           py::arg("optical_filter_transmittance_array"),
           py::arg("refractive_index_array"), py::arg("clip_neg"),
           py::arg("shot_noise"), py::arg("sample_rate"),
           py::arg("responsivity"), py::arg("concentrator_FOV_array"),
           py::arg("E2O_conversion_factor_array"),
           py::arg("O2E_conversion_factor_array"),
           D(OWC_Channel_relative_cplus, make))

      .def("set_emission_angle_array",
           &OWC_Channel_relative_cplus::set_emission_angle_array,
           py::arg("emission_angle_array"),
           D(OWC_Channel_relative_cplus, set_emission_angle_array))

      .def("emission_angle_array",
           &OWC_Channel_relative_cplus::emission_angle_array,
           D(OWC_Channel_relative_cplus, emission_angle_array))

      .def("set_acceptance_angle_array",
           &OWC_Channel_relative_cplus::set_acceptance_angle_array,
           py::arg("acceptance_angle_array"),
           D(OWC_Channel_relative_cplus, set_acceptance_angle_array))

      .def("acceptance_angle_array",
           &OWC_Channel_relative_cplus::acceptance_angle_array,
           D(OWC_Channel_relative_cplus, acceptance_angle_array))

      .def("set_distance_array",
           &OWC_Channel_relative_cplus::set_distance_array,
           py::arg("distance_array"),
           D(OWC_Channel_relative_cplus, set_distance_array))

      .def("distance_array", &OWC_Channel_relative_cplus::distance_array,
           D(OWC_Channel_relative_cplus, distance_array))

      .def("set_lambertian_order_array",
           &OWC_Channel_relative_cplus::set_lambertian_order_array,
           py::arg("lambertian_order_array"),
           D(OWC_Channel_relative_cplus, set_lambertian_order_array))

      .def("lambertian_order_array",
           &OWC_Channel_relative_cplus::lambertian_order_array,
           D(OWC_Channel_relative_cplus, lambertian_order_array))

      ;
}
