/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(OWC_Channel_absolute_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(16dba3a02945d0e9aac2f52b7eb57df9) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/OWC_Channel_absolute_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <OWC_Channel_absolute_cplus_pydoc.h>

void bind_OWC_Channel_absolute_cplus(py::module &m) {

  using OWC_Channel_absolute_cplus = ::gr::owc::OWC_Channel_absolute_cplus;

  py::class_<OWC_Channel_absolute_cplus, gr::sync_block, gr::block,
             gr::basic_block, std::shared_ptr<OWC_Channel_absolute_cplus>>(
      m, "OWC_Channel_absolute_cplus", D(OWC_Channel_absolute_cplus))

      .def(py::init(&OWC_Channel_absolute_cplus::make), py::arg("num_inputs"),
           py::arg("num_outputs"), py::arg("tx_coordinates_array"),
           py::arg("tx_orientation_array"), py::arg("rx_coordinates_array"),
           py::arg("rx_orientation_array"),
           py::arg("tx_lambertian_order_array"),
           py::arg("rx_photosensor_area_array"),
           py::arg("optical_filter_transmittance_array"),
           py::arg("refractive_index_array"), py::arg("clip_neg"),
           py::arg("shot_noise"), py::arg("sample_rate"),
           py::arg("responsivity"), py::arg("concentrator_FOV_array"),
           py::arg("E2O_conversion_factor_array"),
           py::arg("O2E_conversion_factor_array"),
           D(OWC_Channel_absolute_cplus, make))

      .def("set_tx_coordinates_array",
           &OWC_Channel_absolute_cplus::set_tx_coordinates_array,
           py::arg("tx_coordinates_array"),
           D(OWC_Channel_absolute_cplus, set_tx_coordinates_array))

      .def("tx_coordinates_array",
           &OWC_Channel_absolute_cplus::tx_coordinates_array,
           D(OWC_Channel_absolute_cplus, tx_coordinates_array))

      .def("set_tx_orientation_array",
           &OWC_Channel_absolute_cplus::set_tx_orientation_array,
           py::arg("tx_orientation_array"),
           D(OWC_Channel_absolute_cplus, set_tx_orientation_array))

      .def("tx_orientation_array",
           &OWC_Channel_absolute_cplus::tx_orientation_array,
           D(OWC_Channel_absolute_cplus, tx_orientation_array))

      .def("set_rx_coordinates_array",
           &OWC_Channel_absolute_cplus::set_rx_coordinates_array,
           py::arg("rx_coordinates_array"),
           D(OWC_Channel_absolute_cplus, set_rx_coordinates_array))

      .def("rx_coordinates_array",
           &OWC_Channel_absolute_cplus::rx_coordinates_array,
           D(OWC_Channel_absolute_cplus, rx_coordinates_array))

      .def("set_rx_orientation_array",
           &OWC_Channel_absolute_cplus::set_rx_orientation_array,
           py::arg("rx_orientation_array"),
           D(OWC_Channel_absolute_cplus, set_rx_orientation_array))

      .def("rx_orientation_array",
           &OWC_Channel_absolute_cplus::rx_orientation_array,
           D(OWC_Channel_absolute_cplus, rx_orientation_array))

      .def("set_tx_lambertian_order_array",
           &OWC_Channel_absolute_cplus::set_tx_lambertian_order_array,
           py::arg("lambertian_order_array"),
           D(OWC_Channel_absolute_cplus, set_tx_lambertian_order_array))

      .def("tx_lambertian_order_array",
           &OWC_Channel_absolute_cplus::tx_lambertian_order_array,
           D(OWC_Channel_absolute_cplus, tx_lambertian_order_array))

      ;
}
