/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(PAM_Modulator_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(d5268e15073fd57c46df88c2d4887e7f) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/PAM_Modulator_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <PAM_Modulator_cplus_pydoc.h>

void bind_PAM_Modulator_cplus(py::module &m) {

  using PAM_Modulator_cplus = ::gr::owc::PAM_Modulator_cplus;

  py::class_<PAM_Modulator_cplus, gr::sync_interpolator,
             std::shared_ptr<PAM_Modulator_cplus>>(m, "PAM_Modulator_cplus",
                                                   D(PAM_Modulator_cplus))

      .def(py::init(&PAM_Modulator_cplus::make), py::arg("modulation_order"),
           py::arg("max_magnitude"), py::arg("min_magnitude"),
           py::arg("samples_per_symbol"), D(PAM_Modulator_cplus, make))

      .def("set_max_magnitude", &PAM_Modulator_cplus::set_max_magnitude,
           py::arg("max_magnitude"), D(PAM_Modulator_cplus, set_max_magnitude))

      .def("max_magnitude", &PAM_Modulator_cplus::max_magnitude,
           D(PAM_Modulator_cplus, max_magnitude))

      .def("set_min_magnitude", &PAM_Modulator_cplus::set_min_magnitude,
           py::arg("min_magnitude"), D(PAM_Modulator_cplus, set_min_magnitude))

      .def("min_magnitude", &PAM_Modulator_cplus::min_magnitude,
           D(PAM_Modulator_cplus, min_magnitude))

      ;
}
