/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(PAM_Demodulator_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(e745a642c8a791c6cdbc6990fef49766) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/PAM_Demodulator_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <PAM_Demodulator_cplus_pydoc.h>

void bind_PAM_Demodulator_cplus(py::module &m) {

  using PAM_Demodulator_cplus = ::gr::owc::PAM_Demodulator_cplus;

  py::class_<PAM_Demodulator_cplus, gr::sync_decimator,
             std::shared_ptr<PAM_Demodulator_cplus>>(m, "PAM_Demodulator_cplus",
                                                     D(PAM_Demodulator_cplus))

      .def(py::init(&PAM_Demodulator_cplus::make), py::arg("modulation_order"),
           py::arg("max_magnitude"), py::arg("min_magnitude"),
           py::arg("samples_per_symbol"), D(PAM_Demodulator_cplus, make))

      .def("set_max_magnitude", &PAM_Demodulator_cplus::set_max_magnitude,
           py::arg("max_magnitude"),
           D(PAM_Demodulator_cplus, set_max_magnitude))

      .def("max_magnitude", &PAM_Demodulator_cplus::max_magnitude,
           D(PAM_Demodulator_cplus, max_magnitude))

      .def("set_min_magnitude", &PAM_Demodulator_cplus::set_min_magnitude,
           py::arg("min_magnitude"),
           D(PAM_Demodulator_cplus, set_min_magnitude))

      .def("min_magnitude", &PAM_Demodulator_cplus::min_magnitude,
           D(PAM_Demodulator_cplus, min_magnitude))

      ;
}
