/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(PPM_Modulator_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(b77fa39145ff647c343fc8c914ceb1fd) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/PPM_Modulator_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <PPM_Modulator_cplus_pydoc.h>

void bind_PPM_Modulator_cplus(py::module &m) {

  using PPM_Modulator_cplus = ::gr::owc::PPM_Modulator_cplus;

  py::class_<PPM_Modulator_cplus, gr::sync_interpolator,
             std::shared_ptr<PPM_Modulator_cplus>>(m, "PPM_Modulator_cplus",
                                                   D(PPM_Modulator_cplus))

      .def(py::init(&PPM_Modulator_cplus::make), py::arg("max_mag"),
           py::arg("min_mag"), py::arg("samples_per_symbol"),
           py::arg("samples_per_pulse"), py::arg("modulation_order"),
           D(PPM_Modulator_cplus, make))

      .def("set_max_magnitude", &PPM_Modulator_cplus::set_max_magnitude,
           py::arg("max_mag"), D(PPM_Modulator_cplus, set_max_magnitude))

      .def("max_magnitude", &PPM_Modulator_cplus::max_magnitude,
           D(PPM_Modulator_cplus, max_magnitude))

      .def("set_min_magnitude", &PPM_Modulator_cplus::set_min_magnitude,
           py::arg("min_mag"), D(PPM_Modulator_cplus, set_min_magnitude))

      .def("min_magnitude", &PPM_Modulator_cplus::min_magnitude,
           D(PPM_Modulator_cplus, min_magnitude))

      ;
}
