/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(PPM_Demodulator_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(8c8c8232a40774424ff0296fa277711d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/PPM_Demodulator_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <PPM_Demodulator_cplus_pydoc.h>

void bind_PPM_Demodulator_cplus(py::module &m) {

  using PPM_Demodulator_cplus = ::gr::owc::PPM_Demodulator_cplus;

  py::class_<PPM_Demodulator_cplus, gr::sync_decimator,
             std::shared_ptr<PPM_Demodulator_cplus>>(m, "PPM_Demodulator_cplus",
                                                     D(PPM_Demodulator_cplus))

      .def(py::init(&PPM_Demodulator_cplus::make),
           py::arg("samples_per_symbol"), py::arg("samples_per_pulse"),
           py::arg("modulation_order"), D(PPM_Demodulator_cplus, make))

      ;
}
