/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(VPPM_Demodulator_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(0a1d546888e05d6752b2fbf06820c899) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/VPPM_Demodulator_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <VPPM_Demodulator_cplus_pydoc.h>

void bind_VPPM_Demodulator_cplus(py::module &m) {

  using VPPM_Demodulator_cplus = ::gr::owc::VPPM_Demodulator_cplus;

  py::class_<VPPM_Demodulator_cplus, gr::sync_decimator,
             std::shared_ptr<VPPM_Demodulator_cplus>>(
      m, "VPPM_Demodulator_cplus", D(VPPM_Demodulator_cplus))

      .def(py::init(&VPPM_Demodulator_cplus::make),
           py::arg("samples_per_symbol"), py::arg("samples_per_pulse"),
           D(VPPM_Demodulator_cplus, make))

      ;
}
