/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(VPPM_Modulator_cplus.h) */
/* BINDTOOL_HEADER_FILE_HASH(a4be5757627ff4eec5e93c6d25a36cde) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/owc/VPPM_Modulator_cplus.h>
// pydoc.h is automatically generated in the build directory
#include <VPPM_Modulator_cplus_pydoc.h>

void bind_VPPM_Modulator_cplus(py::module &m) {

  using VPPM_Modulator_cplus = ::gr::owc::VPPM_Modulator_cplus;

  py::class_<VPPM_Modulator_cplus, gr::sync_interpolator,
             std::shared_ptr<VPPM_Modulator_cplus>>(m, "VPPM_Modulator_cplus",
                                                    D(VPPM_Modulator_cplus))

      .def(py::init(&VPPM_Modulator_cplus::make), py::arg("max_mag"),
           py::arg("min_mag"), py::arg("samples_per_symbol"),
           py::arg("samples_per_pulse"), D(VPPM_Modulator_cplus, make))

      .def("set_max_magnitude", &VPPM_Modulator_cplus::set_max_magnitude,
           py::arg("max_mag"), D(VPPM_Modulator_cplus, set_max_magnitude))

      .def("max_magnitude", &VPPM_Modulator_cplus::max_magnitude,
           D(VPPM_Modulator_cplus, max_magnitude))

      .def("set_min_magnitude", &VPPM_Modulator_cplus::set_min_magnitude,
           py::arg("min_mag"), D(VPPM_Modulator_cplus, set_min_magnitude))

      .def("min_magnitude", &VPPM_Modulator_cplus::min_magnitude,
           D(VPPM_Modulator_cplus, min_magnitude))

      ;
}
